### ISSUE TITLE
Consider allowsCachingHighQualityImages=NO

### ISSUE THREAD

**Issue by adbl** [olofd/react-native-photos-framework#21]
https://developer.apple.com/reference/photos/phcachingimagemanager/1616959-allowscachinghighqualityimages?language=objc

What is the point in using the cache when displaying single images / few images?

I think it should it be set to `NO`.

There could be a point of using the cache and having `allowsCachingHighQualityImages=YES`, for a some view where images are prepared and cached beforehand.

Maybe having `NO` as default and an method to change it (globally, since it is shared)?

**Comment by olofd** [comment]
Ah. Did not know it defaulted to YES. Will make a global method that can be called to toggle this. Have not used the cache in a while, will test it and make sure it works.

FYI. I'm upgrading this library to use React 0.40 atm. So be aware, you will get linking issues in the next release if you´re still running < 0.40.

**Comment by olofd** [comment]
FYI. Will take a look at this tonight.

**Comment by olofd** [comment]
Implemented in https://github.com/olofd/react-native-photos-framework/commit/495a1e1ff69e348c0da3b944d8520eed653f97f9
