### ISSUE TITLE
need more documentations

### ISSUE THREAD

**Issue by jjhesk** [olofd/react-native-photos-framework#36]
how do we support reading `asset-library://` uri and display that into a `Image` element

**Comment by olofd** [comment]
asset-library:// should work out of the box with react-native. asset-library has nothing to do with this library. Our scheme is photos://. Please explain more.

**Comment by jjhesk** [comment]
do you do it with
```javascript
  let src = this.state.selected_image;

<Image resizeMode="contain" source={{uri:src}}/>
```

**Comment by jjhesk** [comment]
thank you I know what im doing now.
