### ISSUE TITLE
installation configurations

### ISSUE THREAD

**Issue by jjhesk** [olofd/react-native-photos-framework#37]
can we do `react-native install react-native-photos-framework` to do the whole thing?

**Comment by olofd** [comment]
You need to explain more. What do you mean `the whole thing?`. What does it not do?

**Comment by jjhesk** [comment]
I assume that will setup up the necessary linkings with the project folder in iOS xcode that will able to build without errors.

**Comment by olofd** [comment]
@jjhesk Just tested on a fresh project. And running `react-native install react-native-photos-framework` installed, linked and added info.plist-permission to app as expected. You need to be more specific if you have any errors regarding this.
