### ISSUE TITLE
PHAssetCollectionSubtypeSmartAlbumLivePhotos Fail to Compile Issue

### ISSUE THREAD

**Issue by jjhesk** [olofd/react-native-photos-framework#47]
install the latest version 1.0.3
RN 0.43.3
xcode 8.2.1 8C1002

I have got this error

/.../node_modules/react-native-photos-framework/ios/RNPhotosFramework/RCTConvert+RNPhotosFramework.m:103:77: Use of undeclared identifier 'PHAssetCollectionSubtypeSmartAlbumLivePhotos'; did you mean 'PHAssetCollectionSubtypeSmartAlbumVideos'?

/.../node_modules/react-native-photos-framework/ios/RNPhotosFramework/RCTConvert+RNPhotosFramework.m:103:77: Use of undeclared identifier 'PHAssetCollectionSubtypeSmartAlbumLivePhotos'; did you mean 'PHAssetCollectionSubtypeSmartAlbumVideos'?

**Comment by olofd** [comment]
See if it helps to update xcode to version 8.3

**Comment by olofd** [comment]
@jjhesk  Did it help to update?
