### ISSUE TITLE
how to read photos:// prefix file

### ISSUE THREAD

**Issue by jimtang9527** [olofd/react-native-photos-framework#49]
great library,thank you.

![wechatimg13](https://user-images.githubusercontent.com/7098183/26867586-810bb244-4b98-11e7-8ec7-b20688c51741.jpeg)

how to read photos:// prefix file? i hope upload photos to server.

**Comment by olofd** [comment]
You should be able to just send the resource using react-native's built in ajax-support. So just send the resource using the fetch-api. Read the section AJAX in the readme.

**Comment by srameshr** [comment]
@olofd What if the image, is a GIF image and I want to just just show the GIF with the image tag. How do I map photos:// to actual GIF url?
