### ISSUE TITLE
Doesn't show hidden photos?

### ISSUE THREAD

**Issue by DylanVann** [olofd/react-native-photos-framework#5]
I'm seeing hidden photos showing up as blank instead of rendering. Is this some sort of permissions issue?

**Comment by olofd** [comment]
Hmm.. Let me take a look. Brb.

**Comment by DylanVann** [comment]
Thanks. This is an awesome library. I think they're going to need to pull a bunch of this functionality into react-native at some point.

**Comment by olofd** [comment]
@DylanVann Was able to repro and have found the bug. Will see if I can fix it later tonight. I'll keep you posted.

**Comment by olofd** [comment]
@DylanVann Should be fixed now. Just released 0.0.60 with this correction on npm, try install it and let me know if it works as expected.

**Comment by DylanVann** [comment]
Wow, that's great response time. Thanks so much for the fix!

**Comment by olofd** [comment]
Great. Closing for now. Let me know if you have further issues with this and I'll reopen.
