### ISSUE TITLE
Build fails using RN 0.45.1

### ISSUE THREAD

**Issue by rossmartin** [olofd/react-native-photos-framework#50]
I had an existing RN project using 0.43.3 and RNPhotosFramework worked fine.  I updated to the latest (0.45.1) and now I cannot build my project unless I comment out line 3 on `PHChangeObserver.m` shown below.

I also created a new 0.45.1 project and it builds fine up until I add `react-native-photos-framework` and link it.  Here are some screenshots of the issues -

![screen shot 2017-06-19 at 6 51 18 pm](https://user-images.githubusercontent.com/2498502/27310664-7c9d15bc-5521-11e7-9e2a-a5bed7f6c941.png)
![image](https://user-images.githubusercontent.com/2498502/27310589-005cbf66-5521-11e7-9b56-2bcd9ba832a7.png)

**Comment by jasongaare** [comment]
I had the same issue, and simply replaced `RCTBridgeModuleProviderBlock` with `RCTBridgeModuleListProvider` as the error suggested and my project compiled.

**Comment by jasongaare** [comment]
Try deleting your DerivedData folder - worked for me. It was using an older version of React despite a fresh install.

**Comment by rossmartin** [comment]
@jasongaare thanks.  With your suggestion I tried deleting DerivedData via `File->Project Setting` but I've had no luck.

I removed `react-native-photos-framework` and reinstalled it after deleting DerivedData completely but I still have issues.  Any other suggestions?

**Comment by olofd** [comment]
Just did a fresh install on 0.47.2 and it worked. If you need support for older versions you will ave to fork or submit and PR. Reopen if this is still an issue!
