### ISSUE TITLE
Unable to resolve module `react/lib/ReactPropTypes`

### ISSUE THREAD

**Issue by rossmartin** [olofd/react-native-photos-framework#51]
I'm using RN 0.45.1 and the `import ReactPropTypes from 'react/lib/ReactPropTypes'` in [src/index.js](https://github.com/olofd/react-native-photos-framework/blob/master/src/index.js) fails.  It results in _"Module does not exist in the module map..."_

The `PropTypes` module is not used on `src/index.js` so you can safely comment it out.  If `PropTypes` are needed you can use `import ReactPropTypes from 'prop-types'`.

**Comment by gameboyVito** [comment]
Same issue here `Unable to resolve module react/lib/ReactPropTypes`

**Comment by gameboyVito** [comment]
solution: just remove `import ReactPropTypes from 'react/lib/ReactPropTypes';`

**Comment by rossmartin** [comment]
This appears to be fixed by https://github.com/olofd/react-native-photos-framework/commit/360cc57a64af632e18935d4a090053dd56601e83

If the issue is still present just comment out `import ReactPropTypes from 'react/lib/ReactPropTypes';` in `src/index.js`.
