### ISSUE TITLE
Help with 'linker command failed with exit code 1 (use -v to see invocation)'

### ISSUE THREAD

**Issue by BondGoat** [olofd/react-native-photos-framework#55]
Hi there,

I always have this problem when compiling project. Can you help me on this?
My project is using older RN 0.35, is it some the problem?

Thanks.

**Comment by BondGoat** [comment]
Note that I'm using XCode 8.3.2

**Comment by cocoalasca** [comment]
I'm using RN 0.45 when compiling PHChangeObserver.m says file not found when it tries to import the RCBridge+private if I comment that line it gives me a linker error, could this be related or should I create a new thread?
I also had this problem installing in 0.44 I updated thinking that that was maybe the problem but it seems it's not.

**Comment by gre** [comment]
agree there is a problem with `React/RCTBridge+Private.h`

**Comment by olofd** [comment]
Will take a look at this tonight and merge the PR. I'll let you know when it's resolved!

**Comment by gre** [comment]
:+1: thanks

**Comment by gameboyVito** [comment]
@gre any updated?

**Comment by gre** [comment]
@gameboyVito https://github.com/olofd/react-native-photos-framework/pull/58

**Comment by olofd** [comment]
merged. Will close! Big thanks to @gre!

**Comment by facuacostag** [comment]
Sorry, I don't want to open a new issue since I'm having the same problem. Whenever I link this library and try to build the project, it fails.

```
"react": "^16.2.0",
"react-native": "^0.52.2"
````
