### ISSUE TITLE
Can’t run android after installing lib

### ISSUE THREAD

**Issue by zhenkaGo** [olofd/react-native-photos-framework#59]
After installing lib, I faced with the problem after runing android app, in result I have this error `Could not find react-native-photos-framework’s native module. It seems it’s not linked correctly in your xcode-project.`. How to resolve this issue? I want to use this lib only for ios, but for android - default CameraRoll from RN. Thanks for any help.
p.s. IOS works fine

**Comment by RalfNieuwenhuizen** [comment]
https://github.com/olofd/react-native-photos-framework/pull/61

**Comment by olofd** [comment]
Fix merged. Will close.
