### ISSUE TITLE
RCTImageResizer.h problems

### ISSUE THREAD

**Issue by pospetur** [olofd/react-native-photos-framework#66]
I have been using "react-native-image-resizer" in my project and after I added "react-native-photos-framwork' it won't link because of duplicated symbols.

 It looks like you have included most of the ImageResizer code in your project. I have tried to comment out the resizer code and import like this #import <RCTImageResizer/RCTImageResizer.h> 
but it seems there is a mismatch in the APIs.

What is the the bes way to move forward? What do you recommend?

**Comment by olofd** [comment]
Should be fixed on version 0.1.8 on npm. Reopen if it's still an issue!
