### ISSUE TITLE
Unable to resolve module `../react-native/Libraries/EventEmitter/EventEmitter`

### ISSUE THREAD

**Issue by slickdev** [olofd/react-native-photos-framework#68]
Hi there, I am encountering this issue during installation. After a bit of research I came across this issue for a different react-native project which seems like it might be relevant here: https://github.com/invertase/react-native-firebase/issues/386

> Looks like EventEmitter.js was removed from the EventEmitter library as of RN 0.48.

My versions:

"react-native": "0.48.3",
"react-native-photos-framework": "^1.0.8",
platform: iOS

**Comment by Thromshall** [comment]
I am having this issue as well.

**Comment by aforty** [comment]
@olofd this change still isn't on npm with version 1.0.8. Can you push an update?

**Comment by monolithed** [comment]
+1, why is not published yet?

**Comment by 82rules** [comment]
@olofd +1 can we get this fix in a release, I need to update this error during our builds.

**Comment by andresouza** [comment]
this is also affecting us, can we please get an update?

**Comment by tommynordli** [comment]
Please reopen, it's still not published

**Comment by aforty** [comment]
For the love of everything @olofd, can you please push this to npm?

**Comment by 82rules** [comment]
we had to resolve it by locking our package.json to a commit
```"react-native-photos-framework": "https://github.com/olofd/react-native-photos-framework.git#adaa91d8bd13e93cb18c5884d9fde27228a44ebb",```
